### PR TITLE
added typescript support and pubkey recovery function

### PR DESCRIPTION
**Pull request by hoonsubin**
I did not find any type definitions from https://github.com/DefinitelyTyped/DefinitelyTyped and I personally have a lot of use for functions that can safely recover public keys from signatures.
What this PR adds:

- type definitions for all exported functions
- recover ECDSA public key from signature function

I apologize if there are any mistakes with the changes I made. If you can kindly point them out and give me clear instructions on how I should fix it, I will gladly do so.

Thank you!

### CODE REVIEW

**Comment by junderw** [comment]
1. typescript should be devDependencies
2. syntax changes are causing CI to fail
3. DRY with recover

**Comment by junderw** [comment]
Wait, why do we even need typescript as a dependency. You didn't add any typescript.

Also, `"types"` needs to be specified in package.json or else packages won't be able to find the types when they import this.

**Comment by hoonsubin** [comment]
@junderw fixed. I was being an idiot and forgot to clean the package sorry. I think this should address most of the issues. Any more issues, I'll fix them ASAP

**Comment by junderw** [comment]
https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

DRY

recover is 99% a line for line copy of verify.

**Comment by hoonsubin** [comment]
I've tried refactoring the `recover()` function to make it shorter, but due to unit test checks for throw messages (making the `verify()` function use `recover()` means some of the error message will be buried, so I may have to change the unit test if I were to do that), there are still some codes that are reused, specifically this:

```JavaScript
if (!Buffer.isBuffer(signature)) signature = Buffer.from(signature, 'base64')

  const parsed = decodeSignature(signature)
  const hash = magicHash(message, messagePrefix)
  const publicKey = secp256k1.recover(
    hash,
    parsed.signature,
    parsed.recovery,
    parsed.compressed
  )
```

I hope this won't be a big problem (sorry for my noobness)

**Pull request closed without merging**
