### PR TITLE
secp256k1 instead bigi & ecurve

### PR DESCRIPTION
**Pull request by fanatid**
Can be merged when secp256k1-node v3.0.0 will be released :)

### CODE REVIEW

**Comment by dcousens** [comment]
Interesting :),  any reason why you choose to merge it here before the main library?
I'm happy to merge this in any case :+1:

**Comment by dcousens** [comment]
Ping @jprichardson,  have you been keeping up with the developments over there?

**Comment by jprichardson** [comment]
Nice work @fanatid!

> Ping @jprichardson, have you been keeping up with the developments over there?

Not as much as I'd like, I just know that @fanatid is cranking out code non-stop: https://github.com/cryptocoinjs/secp256k1-node/pull/57#commits-pushed-038a41f

**Comment by fanatid** [comment]
PR updated :)

**Comment by dcousens** [comment]
@fanatid does this break the interface? (will review soon)

**Comment by fanatid** [comment]
@dcousens no, interface wasn't changed

**Comment by fanatid** [comment]
need to change:
- [ ] code style
- [ ] tests (mocha -> tape)
- [ ] remove jsdoc
- [ ] remove bitcoinjs-lib as dependency (use [fanatid/varuint-bitcoin](https://github.com/fanatid/varuint-bitcoin), [cryptocoinjs/crypto-hashing](https://github.com/cryptocoinjs/crypto-hashing), [sindresorhus/buffer-equals](https://github.com/sindresorhus/buffer-equals))

**Comment by dcousens** [comment]
I'll still need to manually verify all of this before we deprecate the one in `bitcoinjs-lib`, but,  this is a great head start,  thanks @fanatid :)

**Comment by fanatid** [comment]
@dcousens activate travis for this repository please

**Pull request merged**
